//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.20 at 05:37:34 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://webservice.telemetry.udo.fors.ru/")
package ru.fors.udo.telemetry.webservice;
